//! # Plugin System — Lightweight Extension Hooks for Narrative Sessions
//!
//! Inspired by Liyuan's extension system (lifecycle events, custom tools, hooks),
//! adapted for Kaleido's Rust narrative platform.
//!
//! ## Concepts
//!
//! - **Plugin** trait: lifecycle hooks for narrative events
//! - **PluginRegistry**: manage registered plugins
//! - **NarrativeEvent**: typed events that plugins can react to
//! - **PluginContext**: shared state available to plugins
//!
//! ## Event Types
//!
//! - `SessionCreated` — A new story session begins
//! - `MessageGenerated` — A message is produced by the AI
//! - `WorldStateChanged` — World state mutation occurs
//! - `MemoryExtracted` — Memory tier promotion happened
//! - `SessionCompact` — Session is being compacted (weave)
//! - `SessionEnded` — Session is being destroyed

use crate::story_tavern::TavernMessage;
use std::any::Any;
use std::collections::HashMap;
use std::sync::Arc;

// ─── Context ─────────────────────────────────────────────────────────────────

/// Shared context available to plugins during hook execution.
#[derive(Debug, Clone, Default)]
pub struct PluginContext {
    /// The current session ID, if any.
    pub session_id: Option<String>,
    /// The current character ID being played.
    pub character_id: Option<String>,
    /// Custom key-value store for plugin-to-plugin communication.
    pub metadata: HashMap<String, String>,
}

// ─── Events ──────────────────────────────────────────────────────────────────

/// Categories of narrative events that plugins can hook into.
#[derive(Debug, Clone)]
pub enum NarrativeEvent {
    /// A new session was created (with initial message).
    SessionCreated {
        session_id: String,
        character_id: String,
        initial_message: Option<String>,
    },
    /// A message was generated by the AI.
    MessageGenerated {
        session_id: String,
        message: TavernMessage,
    },
    /// A world state mutation occurred.
    WorldStateChanged {
        session_id: String,
        key: String,
        old_value: Option<String>,
        new_value: String,
    },
    /// Memory tier promotion happened.
    MemoryExtracted {
        session_id: String,
        source_tier: u8,
        target_tier: u8,
        summary: String,
    },
    /// Session context is being compacted.
    SessionCompact {
        session_id: String,
        tokens_before: usize,
        tokens_after: usize,
    },
    /// Session is being ended.
    SessionEnded {
        session_id: String,
        reason: String,
    },
}

// ─── Plugin Hook Results ─────────────────────────────────────────────────────

/// Result indicating whether a hook wants to modify behavior.
#[derive(Debug, Clone)]
pub enum HookAction {
    /// Continue normally.
    Continue,
    /// Skip the default behavior (e.g., skip default message handling).
    Skip,
    /// Replace the default behavior with custom data.
    Override(String),
}

impl Default for HookAction {
    fn default() -> Self {
        HookAction::Continue
    }
}

// ─── Plugin Trait ────────────────────────────────────────────────────────────

/// A plugin can hook into narrative lifecycle events.
///
/// Each method returns `HookAction` to signal whether default processing
/// should continue, be skipped, or be overridden.
pub trait Plugin: Send + Sync {
    /// Unique identifier for this plugin.
    fn id(&self) -> &'static str;

    /// Human-readable name.
    fn name(&self) -> &str {
        self.id()
    }

    /// Called when a new session is created.
    fn on_session_created(
        &self,
        _ctx: &PluginContext,
        _event: &NarrativeEvent,
    ) -> HookAction {
        HookAction::Continue
    }

    /// Called when a message is generated.
    fn on_message_generated(
        &self,
        _ctx: &PluginContext,
        _event: &NarrativeEvent,
        _message: &mut TavernMessage,
    ) -> HookAction {
        HookAction::Continue
    }

    /// Called when world state changes.
    fn on_world_state_changed(
        &self,
        _ctx: &PluginContext,
        _event: &NarrativeEvent,
    ) -> HookAction {
        HookAction::Continue
    }

    /// Called when memory is extracted/promoted.
    fn on_memory_extracted(
        &self,
        _ctx: &PluginContext,
        _event: &NarrativeEvent,
    ) -> HookAction {
        HookAction::Continue
    }

    /// Called during session compaction.
    fn on_session_compact(
        &self,
        _ctx: &PluginContext,
        _event: &NarrativeEvent,
    ) -> HookAction {
        HookAction::Continue
    }

    /// Called when a session ends.
    fn on_session_ended(
        &self,
        _ctx: &PluginContext,
        _event: &NarrativeEvent,
    ) -> HookAction {
        HookAction::Continue
    }

}

// Helper trait for downcasting Arc<dyn Plugin> to concrete type.
// Implemented automatically for all 'static Plugin types.
pub trait AsAny: Any {
    fn as_any_ref(&self) -> &dyn Any;
}
impl<T: Any + Plugin> AsAny for T {
    fn as_any_ref(&self) -> &dyn Any {
        self
    }
}

// ─── Plugin Registry ─────────────────────────────────────────────────────────

/// Manages a collection of plugins and dispatches events to them.
#[derive(Clone, Default)]
pub struct PluginRegistry {
    plugins: Vec<Arc<dyn Plugin>>,
}

impl PluginRegistry {
    /// Create an empty registry.
    pub fn new() -> Self {
        Self {
            plugins: Vec::new(),
        }
    }

    /// Register a plugin.
    pub fn register(&mut self, plugin: impl Plugin + 'static) {
        self.plugins.push(Arc::new(plugin));
    }

    /// Register an already-arc'd plugin.
    pub fn register_arc(&mut self, plugin: Arc<dyn Plugin>) {
        self.plugins.push(plugin);
    }

    /// Remove a plugin by its ID.
    pub fn unregister(&mut self, id: &str) {
        self.plugins.retain(|p| p.id() != id);
    }

    /// Get a reference to a plugin by ID.
    pub fn get(&self, id: &str) -> Option<&Arc<dyn Plugin>> {
        self.plugins.iter().find(|p| p.id() == id)
    }

    /// Check if a plugin is registered.
    pub fn has(&self, id: &str) -> bool {
        self.plugins.iter().any(|p| p.id() == id)
    }

    /// Number of registered plugins.
    pub fn len(&self) -> usize {
        self.plugins.len()
    }

    /// True if no plugins are registered.
    pub fn is_empty(&self) -> bool {
        self.plugins.is_empty()
    }

    /// List all registered plugin IDs.
    pub fn plugin_ids(&self) -> Vec<&'static str> {
        self.plugins.iter().map(|p| p.id()).collect()
    }

    // ─── Event Dispatch ───────────────────────────────────────

    /// Dispatch a session_created event.
    pub fn on_session_created(&self, ctx: &PluginContext, event: &NarrativeEvent) -> Vec<HookAction> {
        self.plugins
            .iter()
            .map(|p| p.on_session_created(ctx, event))
            .collect()
    }

    /// Dispatch a message_generated event.
    /// Plugins can mutate the message.
    pub fn on_message_generated(
        &self,
        ctx: &PluginContext,
        event: &NarrativeEvent,
        message: &mut TavernMessage,
    ) -> Vec<HookAction> {
        self.plugins
            .iter()
            .map(|p| p.on_message_generated(ctx, event, message))
            .collect()
    }

    /// Dispatch a world_state_changed event.
    pub fn on_world_state_changed(&self, ctx: &PluginContext, event: &NarrativeEvent) -> Vec<HookAction> {
        self.plugins
            .iter()
            .map(|p| p.on_world_state_changed(ctx, event))
            .collect()
    }

    /// Dispatch a memory_extracted event.
    pub fn on_memory_extracted(&self, ctx: &PluginContext, event: &NarrativeEvent) -> Vec<HookAction> {
        self.plugins
            .iter()
            .map(|p| p.on_memory_extracted(ctx, event))
            .collect()
    }

    /// Dispatch a session_compact event.
    pub fn on_session_compact(&self, ctx: &PluginContext, event: &NarrativeEvent) -> Vec<HookAction> {
        self.plugins
            .iter()
            .map(|p| p.on_session_compact(ctx, event))
            .collect()
    }

    /// Dispatch a session_ended event.
    pub fn on_session_ended(&self, ctx: &PluginContext, event: &NarrativeEvent) -> Vec<HookAction> {
        self.plugins
            .iter()
            .map(|p| p.on_session_ended(ctx, event))
            .collect()
    }
}

// ─── Built-in Stats Plugin Example ──────────────────────────────────────────

/// Example plugin that tracks session statistics.
#[derive(Clone)]
pub struct StatsPlugin {
    id: &'static str,
}

impl StatsPlugin {
    pub fn new() -> Self {
        Self { id: "stats" }
    }
}

impl Plugin for StatsPlugin {
    fn id(&self) -> &'static str {
        self.id
    }

    fn name(&self) -> &str {
        "Session Stats Tracker"
    }

    fn on_session_created(&self, _ctx: &PluginContext, _event: &NarrativeEvent) -> HookAction {
        HookAction::Continue
    }

    fn on_message_generated(
        &self,
        _ctx: &PluginContext,
        _event: &NarrativeEvent,
        _message: &mut TavernMessage,
    ) -> HookAction {
        HookAction::Continue
    }
}

// ─── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// A test plugin that records events.
    #[derive(Clone)]
    struct TestPlugin {
        id: &'static str,
        #[allow(dead_code)] // [P7] 预留观测字段；当前 hook 实现未记录
        events: Vec<String>,
    }

    impl TestPlugin {
        fn new(id: &'static str) -> Self {
            Self {
                id,
                events: Vec::new(),
            }
        }
    }

    impl Plugin for TestPlugin {
        fn id(&self) -> &'static str {
            self.id
        }

        fn on_session_created(&self, _ctx: &PluginContext, _event: &NarrativeEvent) -> HookAction {
            HookAction::Skip
        }

        fn on_session_ended(&self, _ctx: &PluginContext, _event: &NarrativeEvent) -> HookAction {
            HookAction::Override("archived".into())
        }
    }

    #[test]
    fn test_register_and_dispatch() {
        let mut registry = PluginRegistry::new();
        registry.register(TestPlugin::new("test-1"));

        assert_eq!(registry.len(), 1);
        assert!(registry.has("test-1"));
        assert!(!registry.has("nonexistent"));
    }

    #[test]
    fn test_unregister() {
        let mut registry = PluginRegistry::new();
        registry.register(TestPlugin::new("test-1"));
        registry.register(TestPlugin::new("test-2"));
        assert_eq!(registry.len(), 2);

        registry.unregister("test-1");
        assert_eq!(registry.len(), 1);
        assert!(!registry.has("test-1"));
        assert!(registry.has("test-2"));
    }

    #[test]
    fn test_dispatch_session_created() {
        let mut registry = PluginRegistry::new();
        registry.register(TestPlugin::new("test-1"));

        let ctx = PluginContext::default();
        let event = NarrativeEvent::SessionCreated {
            session_id: "sess-1".into(),
            character_id: "cc-1".into(),
            initial_message: None,
        };

        let results = registry.on_session_created(&ctx, &event);
        assert_eq!(results.len(), 1);
        assert!(matches!(results[0], HookAction::Skip));
    }

    #[test]
    fn test_dispatch_session_ended() {
        let mut registry = PluginRegistry::new();
        registry.register(TestPlugin::new("test-1"));

        let ctx = PluginContext::default();
        let event = NarrativeEvent::SessionEnded {
            session_id: "sess-1".into(),
            reason: "user_closed".into(),
        };

        let results = registry.on_session_ended(&ctx, &event);
        assert_eq!(results.len(), 1);
        match &results[0] {
            HookAction::Override(s) => assert_eq!(s, "archived"),
            _ => panic!("Expected Override"),
        }
    }

    #[test]
    fn test_empty_registry() {
        let registry = PluginRegistry::new();
        assert!(registry.is_empty());
        assert_eq!(registry.len(), 0);

        let ctx = PluginContext::default();
        let event = NarrativeEvent::SessionCreated {
            session_id: "sess-1".into(),
            character_id: "cc-1".into(),
            initial_message: None,
        };
        let results = registry.on_session_created(&ctx, &event);
        assert!(results.is_empty());
    }

    #[test]
    fn test_plugin_ids() {
        let mut registry = PluginRegistry::new();
        registry.register(TestPlugin::new("a"));
        registry.register(TestPlugin::new("b"));

        let ids = registry.plugin_ids();
        assert!(ids.contains(&"a"));
        assert!(ids.contains(&"b"));
        assert_eq!(ids.len(), 2);
    }

    #[test]
    fn test_get_plugin() {
        let mut registry = PluginRegistry::new();
        registry.register(TestPlugin::new("finder"));

        let plugin = registry.get("finder");
        assert!(plugin.is_some());
        assert_eq!(plugin.unwrap().id(), "finder");

        assert!(registry.get("missing").is_none());
    }

    #[test]
    fn test_plugin_context_default() {
        let ctx = PluginContext::default();
        assert!(ctx.session_id.is_none());
        assert!(ctx.character_id.is_none());
        assert!(ctx.metadata.is_empty());
    }

    #[test]
    fn test_stats_plugin() {
        let plugin = StatsPlugin::new();
        assert_eq!(plugin.id(), "stats");
        assert_eq!(plugin.name(), "Session Stats Tracker");
    }

    #[test]
    fn test_register_arc() {
        let mut registry = PluginRegistry::new();
        registry.register_arc(Arc::new(StatsPlugin::new()));
        assert!(registry.has("stats"));
    }

    #[test]
    fn test_narrative_event_debug() {
        let event = NarrativeEvent::MemoryExtracted {
            session_id: "s-1".into(),
            source_tier: 4,
            target_tier: 3,
            summary: "test".into(),
        };
        let debug = format!("{:?}", event);
        assert!(debug.contains("MemoryExtracted"));
        assert!(debug.contains("s-1"));
    }

    #[test]
    fn test_multiple_plugins_aggregate() {
        let mut registry = PluginRegistry::new();
        registry.register(TestPlugin::new("p1"));
        registry.register(TestPlugin::new("p2"));

        let ctx = PluginContext::default();
        let event = NarrativeEvent::SessionCreated {
            session_id: "s-1".into(),
            character_id: "cc-1".into(),
            initial_message: None,
        };

        let results = registry.on_session_created(&ctx, &event);
        assert_eq!(results.len(), 2);
        assert!(results.iter().all(|r| matches!(r, HookAction::Skip)));
    }
}
