/**
 * src/js/agent.js — Agent 沙箱/爬取/EmbedLab/登录域真 ESM 模块（P1-3 S2.16）。
 * 出边：renderAsVisual/loadEmbedLabStatus/loadEmbedLabEvents（Mechanism Y；
 * jobs 经既有 __kaleidoAgent 门面）。入边经门面访问器（见各 helper）。
 */
import { $ } from './dom.js';
import { api, setApiBase, getSseTicket } from './api.js';
import { showLogin, showMain } from './api_shell.js';
import { uid, TOKEN_KEY, USER_KEY } from './utils.js';

/* local copy (keyboard.js/tavern.js precedent) */
function escapeHtml(s) {
  return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

import { renderMessages, saveSession, refreshSessions, closeEs, showChatSetup,
  setupChatStart, ensureSession, sendMessage, stopStream } from './chat.js';

const __auth = () => window.__kaleidoAuthState;
const __t6 = () => window.__kaleidoTabs;
const __p4 = () => window.__kaleidoPartner;
const __set = () => window.__kaleidoSettings;

/* Agent */
  function renderAsVisual(data) {
    const el = $('as-visual');
    if (!el) return;
    const sessions = (data && data.sessions) || [];
    if (!sessions.length) {
      el.classList.add('hidden');
      return;
    }
    el.classList.remove('hidden');
    el.innerHTML = '<div class="as-visual-header"><span>Agent 会话列表 (' + sessions.length + ')</span></div>';
    for (const s of sessions) {
      const card = document.createElement('div');
      card.className = 'as-visual-card';
      const status = s.status || 'unknown';
      const statusCls = status === 'running' ? 'tag-running' : (status === 'done' ? 'tag-done' : 'tag-idle');
      card.innerHTML = [
        '<div class="as-vc-top">',
        '  <span class="as-vc-title">' + escapeHtml(s.title || '无标题') + '</span>',
        '  <span class="tag ' + statusCls + '">' + escapeHtml(status) + '</span>',
        '</div>',
        '<div class="as-vc-id">' + escapeHtml(s.id) + '</div>',
        '<div class="as-vc-meta">',
        '  <span>' + (s.messageCount || s.msgCount || 0) + ' 条消息</span>',
        '  <span>' + (s.createdAt ? new Date(s.createdAt).toLocaleString() : '') + '</span>',
        '</div>',
      ].join('');
      card.onclick = () => {
        if ($('as-id')) $('as-id').value = s.id;
        // Auto-load on click
        if ($('as-load')) $('as-load').click();
      };
      el.appendChild(card);
    }
  }

  async function asRun(dry) {
    const id = ($('as-id') && $('as-id').value || '').trim();
    if (!id) throw new Error('session id required');
    const maxRounds = parseInt(($('as-max-rounds') && $('as-max-rounds').value) || '4', 10);
    const body = {
      message: ($('as-msg') && $('as-msg').value || '').trim() || undefined,
      maxToolRounds: isNaN(maxRounds) ? 4 : maxRounds,
      dryRun: !!dry,
      tools: dry ? [{ name: 'list', arguments: { path: 'state' } }] : undefined,
    };
    const data = await api('/api/v1/agent/sessions/' + encodeURIComponent(id) + '/run', {
      method: 'POST',
      body: JSON.stringify(body),
    });
    setPanel('as-out', 'as-msg-status', data);
    return data;
  }
  if ($('as-run-dry')) {
    $('as-run-dry').onclick = async () => {
      try { await asRun(true); } catch (e) { setPanel('as-out', 'as-msg-status', null, e); }
    };
  }
  if ($('as-run')) {
    $('as-run').onclick = async () => {
      try { await asRun(false); } catch (e) { setPanel('as-out', 'as-msg-status', null, e); }
    };
  }
  if ($('agent-read')) {
    $('agent-read').onclick = async () => {
      try {
        const path = ($('agent-path').value || '').trim();
        if (!path) throw new Error('path required for read');
        const data = await api('/api/v1/agent/tools/read', {
          method: 'POST',
          body: JSON.stringify({ path }),
        });
        setPanel('agent-out', 'agent-msg', data);
      } catch (e) {
        setPanel('agent-out', 'agent-msg', null, e);
      }
    };
  }
  if ($('agent-write')) {
    $('agent-write').onclick = async () => {
      try {
        const path = ($('agent-path').value || '').trim();
        if (!path) throw new Error('path required for write');
        const sample = '# generated by kaleido Web\n\nHello from agent write.\n';
        const dir = path.includes('/') ? path.split('/').slice(0, -1).join('/') : '';
        let data;
        try {
          data = await api('/api/v1/agent/tools/write', {
            method: 'POST',
            body: JSON.stringify({ path, content: sample }),
          });
        } catch (e2) {
          if (dir && e2 && e2.message && e2.message.includes('directory')) {
            await api('/api/v1/agent/tools/write', {
              method: 'POST',
              body: JSON.stringify({ path: dir + '/.keep', content: '' }),
            });
            data = await api('/api/v1/agent/tools/write', {
              method: 'POST',
              body: JSON.stringify({ path, content: sample }),
            });
          } else {
            throw e2;
          }
        }
        setPanel('agent-out', 'agent-msg', data);
      } catch (e) {
        setPanel('agent-out', 'agent-msg', null, e);
      }
    };
  }
  if ($('agent-bash')) {
    $('agent-bash').onclick = async () => {
      try {
        const command = ($('agent-bash-cmd').value || '').trim() || 'echo hello';
        const data = await api('/api/v1/agent/tools/bash', {
          method: 'POST',
          body: JSON.stringify({ command }),
        });
        setPanel('agent-out', 'agent-msg', data);
      } catch (e) {
        setPanel('agent-out', 'agent-msg', null, e);
      }
    };
  }

  // ─── Crawler UI helpers ──────────────────────────────────────
  function showCrawlMeta(meta, title) {
    const panel = $('crawl-meta-panel');
    const display = $('crawl-meta-display');
    if (!panel || !display) return;
    panel.classList.remove('hidden');
    const statusText = meta.creation_status === 0 ? '连载中' : meta.creation_status === 1 ? '已完结' : '未知';
    const wordText = meta.word_number > 10000 ? (meta.word_number / 10000).toFixed(1) + '万字' : meta.word_number + '字';
    const rows = [
      ['书名', title || '—'],
      ['作者', meta.author || '—'],
      ['分类', meta.category || '—'],
      ['状态', statusText],
      ['字数', wordText],
      ['阅读量', meta.read_count > 10000 ? (meta.read_count / 10000).toFixed(1) + '万' : meta.read_count],
      ['总章数', meta.chapter_total || '—'],
      ['最新章节', meta.last_chapter_title || '—'],
      ['简介', (meta.abstract_text || '—').slice(0, 200) + (meta.abstract_text && meta.abstract_text.length > 200 ? '...' : '')],
    ];
    display.innerHTML = rows.map(([k, v]) =>
      `<span style="font-weight:600;color:var(--accent,#d97757);">${k}</span><span>${escapeHtml(String(v))}</span>`
    ).join('');
  }

  function showCrawlProgress(data) {
    const panel = $('crawl-progress-panel');
    const list = $('crawl-progress-list');
    if (!panel || !list) return;
    panel.classList.remove('hidden');
    if (!data || !data.ok || !data.progress) {
      list.innerHTML = '<span>暂无后台爬取任务</span>';
      return;
    }
    const items = Array.isArray(data.progress) ? data.progress : [data.progress];
    if (!items.length) {
      list.innerHTML = '<span>暂无后台爬取任务</span>';
      return;
    }
    list.innerHTML = items.map(p => {
      const pct = p.total > 0 ? Math.round(p.fetched / p.total * 100) : 0;
      const bar = `<div style="background:#333;border-radius:4px;height:8px;margin:4px 0;overflow:hidden;"><div style="background:#d97757;width:${pct}%;height:100%;border-radius:4px;"></div></div>`;
      const statusIcon = p.status === 'done' ? '✅' : p.status === 'running' ? '⏳' : '❌';
      return `<div style="margin-bottom:8px;padding:6px 8px;background:rgba(255,255,255,0.04);border-radius:6px;">
        <div>${statusIcon} <strong>${escapeHtml(p.title || '未命名')}</strong> — ${p.fetched}/${p.total} 章 (${pct}%)${p.skipped ? ` · 跳过 ${p.skipped}` : ''}</div>
        ${bar}
        ${p.current_chapter ? `<div class="muted sm">当前: ${escapeHtml(p.current_chapter)}</div>` : ''}
        ${p.output_path ? `<div class="muted sm">输出: ${escapeHtml(p.output_path)}</div>` : ''}
      </div>`;
    }).join('');
  }

  if ($('crawl-run')) {
    $('crawl-run').onclick = async () => {
      try {
        const url = ($('crawl-url').value || '').trim();
        const articleId = ($('crawl-article-id').value || '').trim();
        const body = {};
        if (articleId) body.articleId = articleId;
        else if (url && url !== 'https://fanqienovel.com/reader/0') body.url = url;
        if ($('crawl-save') && $('crawl-save').checked) body.save = true;
        if (!body.url && !body.articleId) throw new Error('url or articleId required');
        const data = await api('/api/v1/crawler/fanqie', {
          method: 'POST',
          body: JSON.stringify(body),
        });
        setPanel('crawl-out', 'crawl-msg', data);
        // 如果响应里有 meta，展示元数据
        if (data && data.meta && data.meta.author) {
          showCrawlMeta(data.meta, data.title);
        }
        // 如果有 savedPath 提示后台爬取
        if (data && data.savedPath && data.chaptersFetched > 50) {
          if ($('crawl-msg')) $('crawl-msg').textContent = '后台爬取已启动，点击「后台进度」查看';
        }
      } catch (e) {
        setPanel('crawl-out', 'crawl-msg', null, e);
      }
    };
  }

  // 查询元数据按钮
  if ($('crawl-meta-btn')) {
    $('crawl-meta-btn').onclick = async () => {
      try {
        const url = ($('crawl-url').value || '').trim();
        const articleId = ($('crawl-article-id').value || '').trim();
        let query = '';
        if (articleId) query = '?bookId=' + encodeURIComponent(articleId);
        else if (url && url !== 'https://fanqienovel.com/reader/0') query = '?url=' + encodeURIComponent(url);
        else throw new Error('请输入链接或文章ID');
        const data = await api('/api/v1/crawler/fanqie/meta' + query);
        if (data && data.ok && data.meta) {
          showCrawlMeta(data.meta, data.title);
        } else {
          if ($('crawl-msg')) $('crawl-msg').textContent = '未获取到元数据';
        }
      } catch (e) {
        setPanel('crawl-out', 'crawl-msg', null, e);
      }
    };
  }

  // 后台进度按钮
  if ($('crawl-progress-btn')) {
    $('crawl-progress-btn').onclick = async () => {
      try {
        const data = await api('/api/v1/crawler/fanqie/progress');
        showCrawlProgress(data);
      } catch (e) {
        setPanel('crawl-out', 'crawl-msg', null, e);
      }
    };
  }

  // 搜索按钮
  if ($('crawl-search-btn')) {
    $('crawl-search-btn').onclick = async () => {
      const q = ($('crawl-search-input').value || '').trim();
      const resultsDiv = $('crawl-search-results');
      if (!q) { if (resultsDiv) resultsDiv.innerHTML = '<span class="muted">请输入书名</span>'; return; }
      if (resultsDiv) resultsDiv.innerHTML = '<span class="muted">搜索中...</span>';
      try {
        const data = await api('/api/v1/crawler/fanqie/search?q=' + encodeURIComponent(q));
        if (!data || !data.ok || !data.results || !data.results.length) {
          if (resultsDiv) resultsDiv.innerHTML = '<span class="muted">未搜索到相关小说</span>';
          return;
        }
        resultsDiv.innerHTML = data.results.map(r => {
          const status = r.creation_status === 0 ? '连载中' : r.creation_status === 1 ? '已完结' : '';
          const word = r.word_number > 10000 ? (r.word_number / 10000).toFixed(0) + '万字' : '';
          const cover = r.cover_url ? `<img src="${escapeHtml(r.cover_url)}" class="crawl-cover" loading="lazy" alt="" />` : '';
          return `<div class="crawl-search-item" class="crawl-search-item" data-bookid="${escapeHtml(r.book_id || '')}">
            ${cover}
            <div class="flex-1">
              <div><strong>${escapeHtml(r.title || '未命名')}</strong> ${status ? `<span class="muted sm">${status}</span>` : ''} ${word ? `<span class="muted sm">${word}</span>` : ''}</div>
              ${r.author ? `<div class="muted sm">${escapeHtml(r.author)}</div>` : ''}
              ${r.category ? `<div class="muted sm">${escapeHtml(r.category)}</div>` : ''}
              ${r.abstract ? `<div class="muted sm" class="crawl-abstract">${escapeHtml(r.abstract)}</div>` : ''}
            </div>
            <button type="button" class="btn-secondary sm" class="align-self-center" data-bookid="${escapeHtml(r.book_id || '')}">填入ID</button>
          </div>`;
        }).join('');
        // 点击搜索结果填入 book_id
        resultsDiv.querySelectorAll('[data-bookid]').forEach(btn => {
          btn.onclick = (e) => {
            e.stopPropagation();
            const bid = btn.getAttribute('data-bookid');
            if (bid && $('crawl-article-id')) $('crawl-article-id').value = bid;
            if ($('crawl-msg')) $('crawl-msg').textContent = '已填入ID: ' + bid;
          };
        });
        // 点击整个卡片也填入ID
        resultsDiv.querySelectorAll('.crawl-search-item').forEach(item => {
          item.onclick = () => {
            const bid = item.getAttribute('data-bookid');
            if (bid && $('crawl-article-id')) $('crawl-article-id').value = bid;
          };
        });
      } catch (e) {
        if (resultsDiv) resultsDiv.innerHTML = '<span class="muted">搜索失败: ' + escapeHtml(e.message || String(e)) + '</span>';
      }
    };
    // 回车搜索
    if ($('crawl-search-input')) {
      $('crawl-search-input').addEventListener('keydown', (e) => {
        if (e.key === 'Enter') { e.preventDefault(); $('crawl-search-btn').click(); }
      });
    }
  }

  $('login-btn').onclick = async () => {
    loginErr.textContent = '';
    try {
      // Persist server URL for Android / cross-origin shells
      if ($('api-base')) {
        setApiBase($('api-base').value);
      }
      const body = {
        username: $('username').value.trim(),
        password: $('password').value,
      };
      const res = await api('/api/v1/auth/login', { method: 'POST', body: JSON.stringify(body) });
      __auth().token = res.__auth().token;
      __auth().username = res.__auth().username;
      __auth().anWsId = res.workspace_id || '';
      localStorage.setItem('kaleido_ws_id', __auth().anWsId);
      localStorage.setItem(TOKEN_KEY, __auth().token);
      localStorage.setItem(USER_KEY, __auth().username);
      showMain();
      await Promise.all([__p4().loadPartner(), __set().loadSettings(), ensureSession()]);
      __t6().switchTab(__t6().parseLocationHash() || __t6().currentTab || 'home', { fromHash: true });
    } catch (e) {
      const raw = e && e.message ? e.message : String(e);
      let msg = raw;
      if (/too many active sessions/i.test(raw)) {
        msg = '登录名额已满（会话过多）。请稍后重试，或联系管理员清理会话。';
      } else if (/too many login attempts/i.test(raw)) {
        msg = '登录尝试过于频繁，请稍后再试。';
      } else if (/429/.test(raw) || /RateLimited/i.test(raw)) {
        msg = '请求过于频繁或服务限流，请稍后再试。';
      } else if (typeof friendlyError === 'function') {
        msg = friendlyError(e);
      }
      loginErr.textContent = msg;
    }
  };

  // S5-W2 T5 Skills
  if ($('sk-list')) {
    $('sk-list').onclick = async () => {
      try {
        const data = await api('/api/v1/skills');
        setPanel('sk-out', 'sk-msg', data);
      } catch (e) { setPanel('sk-out', 'sk-msg', null, e); }
    };
  }
  if ($('sk-import')) {
    $('sk-import').onclick = async () => {
      try {
        const body = {
          name: ($('sk-name').value || '').trim(),
          description: ($('sk-desc').value || '').trim() || undefined,
          content: $('sk-content').value || '',
        };
        const data = await api('/api/v1/skills', { method: 'POST', body: JSON.stringify(body) });
        setPanel('sk-out', 'sk-msg', data);
      } catch (e) { setPanel('sk-out', 'sk-msg', null, e); }
    };
  }
  if ($('sk-delete')) {
    $('sk-delete').onclick = async () => {
      try {
        const name = ($('sk-name').value || '').trim();
        if (!name) throw new Error('name required');
        const data = await api('/api/v1/skills/' + encodeURIComponent(name), { method: 'DELETE' });
        setPanel('sk-out', 'sk-msg', data);
      } catch (e) { setPanel('sk-out', 'sk-msg', null, e); }
    };
  }

  // S5-W2 T6 de-AI / memory
  if ($('deai-run')) {
    $('deai-run').onclick = async () => {
      try {
        const body = {
          text: $('deai-text').value || '',
          mode: ($('deai-mode') && $('deai-mode').value) || 'humanize',
        };
        const data = await api('/api/v1/deai/summarize', { method: 'POST', body: JSON.stringify(body) });
        setPanel('deai-out', 'deai-msg', data);
      } catch (e) { setPanel('deai-out', 'deai-msg', null, e); }
    };
  }
  if ($('mem-analyze')) {
    $('mem-analyze').onclick = async () => {
      try {
        const body = {
          characterName: ($('mem-name').value || '').trim() || undefined,
          memory: $('mem-text').value || '',
        };
        const data = await api('/api/v1/partner/analyze-memory', { method: 'POST', body: JSON.stringify(body) });
        setPanel('mem-out', 'deai-msg', data);
      } catch (e) { setPanel('mem-out', 'deai-msg', null, e); }
    };
  }
  if ($('mem-optimize')) {
    $('mem-optimize').onclick = async () => {
      try {
        const body = {
          characterName: ($('mem-name').value || '').trim() || undefined,
          memory: $('mem-text').value || '',
        };
        const data = await api('/api/v1/partner/optimize-memory', { method: 'POST', body: JSON.stringify(body) });
        setPanel('mem-out', 'deai-msg', data);
      } catch (e) { setPanel('mem-out', 'deai-msg', null, e); }
    };
  }

  // S5-W2 T7 stats
  async function statsGet(path) {
    const data = await api(path);
    setPanel('stats-out', 'stats-msg', data);
  }
  if ($('stats-interactions')) {
    $('stats-interactions').onclick = async () => {
      try { await statsGet('/api/v1/stats/interactions'); } catch (e) { setPanel('stats-out', 'stats-msg', null, e); }
    };
  }
  if ($('stats-writing')) {
    $('stats-writing').onclick = async () => {
      try { await statsGet('/api/v1/stats/writing'); } catch (e) { setPanel('stats-out', 'stats-msg', null, e); }
    };
  }
  if ($('stats-summary')) {
    $('stats-summary').onclick = async () => {
      try { await statsGet('/api/v1/stats/work-summary'); } catch (e) { setPanel('stats-out', 'stats-msg', null, e); }
    };
  }

  // ===== Embed Lab (向量实验室) =====
  const EMBEDLAB_PRESET = [
    '雨巷里青衣门杀手收起狙击枪',
    '窄巷夜雨，刺客把长枪藏进衣袖',
    '今天股市大涨，新能源板块领涨',
  ].join('\n');

  function cosineSim(a, b) {
    if (!a || !b || a.length !== b.length || !a.length) return 0;
    let dot = 0, na = 0, nb = 0;
    for (let i = 0; i < a.length; i++) {
      const x = a[i], y = b[i];
      dot += x * y;
      na += x * x;
      nb += y * y;
    }
    const d = Math.sqrt(na) * Math.sqrt(nb);
    return d ? dot / d : 0;
  }

  function shortLabel(s, n) {
    const t = String(s || '').replace(/\s+/g, ' ').trim();
    if (t.length <= n) return t;
    return t.slice(0, n - 1) + '…';
  }

  function heatClass(score) {
    if (score >= 0.75) return 'hi';
    if (score >= 0.45) return 'mid';
    return 'lo';
  }

  function setEmbedLabStatus(emb) {
    emb = emb || {};
    const ready = !!emb.ready;
    const readyEl = $('el-ready');
    if (readyEl) {
      readyEl.textContent = ready ? '是' : '否';
      readyEl.classList.toggle('ok', ready);
      readyEl.classList.toggle('bad', !ready);
    }
    if ($('el-backend')) $('el-backend').textContent = emb.backend || '—';
    if ($('el-dim')) $('el-dim').textContent = emb.dim != null ? String(emb.dim) : '—';
    if ($('el-model')) $('el-model').textContent = emb.model || '—';
    if ($('el-cache')) $('el-cache').textContent = emb.cache ? ('缓存：' + emb.cache) : '';
  }

  async function loadEmbedLabStatus() {
    try {
      const data = await api('/api/v1/embed/status');
      setEmbedLabStatus((data && data.embedding) || data || {});
      if ($('embedlab-msg')) $('embedlab-msg').textContent = '';
    } catch (e) {
      setEmbedLabStatus({ ready: false, backend: 'error' });
      if ($('embedlab-msg')) $('embedlab-msg').textContent = '状态失败：' + (e.message || e);
      showToast('向量实验室：' + (e.message || e), 'error');
    }
  }

  function stL2Events(sess) {
    const mem = (sess && (sess.memoryL2 || sess.memory_l2)) || {};
    return (mem.events || []).filter(Boolean);
  }

  function renderEmbedLabEvents(events) {
    const list = $('el-events-list');
    if (!list) return;
    if (!events || !events.length) {
      list.innerHTML = '';
      return;
    }
    list.innerHTML = events.map((e, i) => {
      const actors = (e.actors || []).slice(0, 3).map((a) =>
        '<span class="el-event-actor">' + escapeHtml(a) + '</span>').join('');
      const hasEmb = !!(e.embedding && e.embedding.length);
      return (
        '<div class="el-event" title="' + escapeHtml(e.summary || '') + '">' +
          '<span class="el-event-rank">#' + (i + 1) + '</span>' +
          '<span class="el-event-body">' +
            '<span class="el-event-kind">' + escapeHtml(e.kind || 'event') + '</span>' +
            '<span class="el-event-sum">' + escapeHtml(e.summary || '') + '</span>' +
            '<span class="el-event-sub muted sm">t' + (e.turn || '?') + (e.nodeId ? ' · ' + escapeHtml(e.nodeId) : '') + '</span>' +
            (actors ? '<span class="el-event-actors">' + actors + '</span>' : '') +
          '</span>' +
          '<span class="el-event-badge' + (hasEmb ? ' ok' : '') + '">' + (hasEmb ? '已嵌入' : '未嵌入') + '</span>' +
        '</div>'
      );
    }).join('');
  }

  async function loadEmbedLabEvents() {
    const list = $('el-events-list');
    if (!list) return;
    const local = stL2Events(tavernSession);
    if (local.length) {
      renderEmbedLabEvents(local);
      return;
    }
    try {
      const data = await api('/api/v1/story-tavern/sessions');
      const sessions = (data && data.sessions) || [];
      for (const s of sessions) {
        const id = s.__ch().sessionId || s.id;
        if (!id) continue;
        let detail;
        try {
          detail = await api('/api/v1/story-tavern/sessions/' + encodeURIComponent(id));
        } catch (_) { continue; }
        const ev = stL2Events(detail);
        if (ev.length) {
          renderEmbedLabEvents(ev);
          return;
        }
      }
      renderEmbedLabEvents(null);
    } catch (e) {
      renderEmbedLabEvents(null);
      if ($('embedlab-msg')) $('embedlab-msg').textContent = '语义事件加载失败：' + (e.message || e);
    }
  }

  function renderEmbedLabMatrix(texts, vecs) {
    const n = texts.length;
    const matrix = $('embedlab-matrix');
    const pairs = $('embedlab-pairs');
    if (!matrix || !pairs) return;
    if (n < 2) {
      matrix.hidden = true;
      matrix.innerHTML = '';
      pairs.innerHTML = '';
      return;
    }
    let html = '<table><thead><tr><th></th>';
    for (let j = 0; j < n; j++) html += '<th title="' + texts[j].replace(/"/g, '&quot;') + '">#' + (j + 1) + '</th>';
    html += '</tr></thead><tbody>';
    const pairRows = [];
    for (let i = 0; i < n; i++) {
      html += '<tr><th title="' + texts[i].replace(/"/g, '&quot;') + '">#' + (i + 1) + ' ' + shortLabel(texts[i], 10) + '</th>';
      for (let j = 0; j < n; j++) {
        const s = cosineSim(vecs[i], vecs[j]);
        const cls = i === j ? 'diag' : heatClass(s);
        html += '<td class="' + cls + '" title="' + s.toFixed(4) + '">' + (i === j ? '1' : s.toFixed(2)) + '</td>';
        if (j > i) {
          pairRows.push({ i, j, s, a: texts[i], b: texts[j] });
        }
      }
      html += '</tr>';
    }
    html += '</tbody></table>';
    matrix.innerHTML = html;
    matrix.hidden = false;
    pairRows.sort((x, y) => y.s - x.s);
    pairs.innerHTML = pairRows.map((p) => {
      const pct = Math.max(0, Math.min(100, Math.round(((p.s + 1) / 2) * 100)));
      return (
        '<div class="embedlab-pair ' + heatClass(p.s) + '">' +
          '<div class="pair-score">' + p.s.toFixed(4) + '</div>' +
          '<div class="pair-body">' +
            '<div class="pair-line"><span class="idx">#' + (p.i + 1) + '</span> ' + shortLabel(p.a, 48) + '</div>' +
            '<div class="pair-line"><span class="idx">#' + (p.j + 1) + '</span> ' + shortLabel(p.b, 48) + '</div>' +
            '<div class="pair-bar"><i style="width:' + pct + '%"></i></div>' +
          '</div>' +
        '</div>'
      );
    }).join('');
  }

  async function runEmbedLab() {
    const raw = ($('embedlab-texts') && $('embedlab-texts').value) || '';
    const texts = raw.split(/\r?\n/).map((s) => s.trim()).filter(Boolean);
    if (!texts.length) {
      if ($('embedlab-msg')) $('embedlab-msg').textContent = '至少输入 1 行文本';
      return;
    }
    if (texts.length > 12) {
      if ($('embedlab-msg')) $('embedlab-msg').textContent = '一次最多 12 行（避免刷爆）';
      return;
    }
    if ($('embedlab-run')) $('embedlab-run').disabled = true;
    if ($('embedlab-msg')) $('embedlab-msg').textContent = '计算中…';
    if ($('embedlab-meta')) $('embedlab-meta').textContent = '';
    const t0 = performance.now();
    try {
      const data = await api('/api/v1/embeddings', {
        method: 'POST',
        body: JSON.stringify({ input: texts, model: 'BAAI/bge-small-zh-v1.5' }),
      });
      const ms = Math.round(performance.now() - t0);
      const rows = (data && data.data) || [];
      const vecs = rows.map((r) => r.embedding || []);
      const dim = vecs[0] ? vecs[0].length : 0;
      const backend = (data && data.backend) || '—';
      if ($('embedlab-meta')) {
        $('embedlab-meta').textContent =
          backend + ' · dim ' + dim + ' · n=' + texts.length + ' · ' + ms + 'ms';
      }
      // refresh status pills from response if possible
      if ($('el-backend')) $('el-backend').textContent = backend;
      if ($('el-dim') && dim) $('el-dim').textContent = String(dim);
      if ($('el-ready')) {
        $('el-ready').textContent = '是';
        $('el-ready').classList.add('ok');
        $('el-ready').classList.remove('bad');
      }
      renderEmbedLabMatrix(texts, vecs);
      const preview = {
        backend,
        model: data && data.model,
        n: texts.length,
        dim,
        latency_ms: ms,
        first4: vecs[0] ? vecs[0].slice(0, 4) : null,
      };
      if ($('embedlab-out')) {
        $('embedlab-out').hidden = false;
        $('embedlab-out').textContent = JSON.stringify(preview, null, 2);
      }
      if ($('embedlab-msg')) {
        if (texts.length >= 2) {
          const best = cosineSim(vecs[0], vecs[1]);
          $('embedlab-msg').textContent =
            '完成。近义对应明显高过跨域（示例 #1↔#2 约 0.7，#1↔#3 约 0.25）。当前 #1↔#2 = ' +
            best.toFixed(4);
        } else {
          $('embedlab-msg').textContent = '完成（单条，无 pairwise）';
        }
      }
    } catch (e) {
      if ($('embedlab-msg')) $('embedlab-msg').textContent = '失败：' + (e.message || e);
      if ($('embedlab-out')) {
        $('embedlab-out').hidden = false;
        $('embedlab-out').textContent = String(e.message || e);
      }
    } finally {
      if ($('embedlab-run')) $('embedlab-run').disabled = false;
    }
  }

  if ($('embedlab-refresh')) {
    $('embedlab-refresh').onclick = () => loadEmbedLabStatus();
  }
  if ($('el-events-refresh')) {
    $('el-events-refresh').onclick = () => loadEmbedLabEvents();
  }
  if ($('embedlab-run')) {
    $('embedlab-run').onclick = () => runEmbedLab();
  }
  if ($('embedlab-preset')) {
    $('embedlab-preset').onclick = () => {
      if ($('embedlab-texts')) $('embedlab-texts').value = EMBEDLAB_PRESET;
      if ($('embedlab-msg')) $('embedlab-msg').textContent = '已重置示例文本';
    };
  }

  $('search-global-btn').onclick = () => {
    openGlobalSearch();
  };

  $('logout-btn').onclick = async () => {
    try { await api('/api/v1/auth/logout', { method: 'POST', body: '{}' }); } catch (_) {}
    __auth().token = '';
    localStorage.removeItem(TOKEN_KEY);
    localStorage.removeItem(USER_KEY);
    closeEs();
    showLogin();
  };

  $('new-session').onclick = async () => {
    __ch().sessionId = uid('partner-session');
    localStorage.setItem(SID_KEY, __ch().sessionId);
    __ch().messages = [];
    renderMessages();
    await saveSession('新对话');
    await refreshSessions();
    // S9.4: new session → back to options view for choosing partner config
    showChatSetup();
  };

  // S9.4: 开始对话 button in the options view
  setupChatStart();

  $('composer').onsubmit = (e) => {
    e.preventDefault();
    sendMessage(input.value);
  };

  input.addEventListener('keydown', (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage(input.value);
    }
  });

  stopBtn.onclick = __ch().stopStream;

  (async () => {
    // initial hash → tab (even before login so chrome title is ready)
    if (location.hash) {
      __t6().currentTab = __t6().parseLocationHash();
    } else {
      __t6().writeHashForTab(__t6().currentTab);
    }
    if (__auth().token) {
      try {
        await api('/api/v1/me');
        showMain();
        await Promise.all([__p4().loadPartner(), __set().loadSettings(), ensureSession()]);
        // re-apply hash after data load (bond needs partner)
        __t6().switchTab(__t6().parseLocationHash() || __t6().currentTab, { fromHash: true });
        return;
      } catch (_) {
        __auth().token = '';
        localStorage.removeItem(TOKEN_KEY);
      }
    }
    showLogin();
  })();

  // ===== ST-3 Story Tavern UI =====
  // S2.10: PLAYABLE_LABELS / ST_ICONS moved to src/js/utils.js (tavern.js imports them;
  // this closure keeps seeing them via the converted[] utils import line).

/* S2.11: agent facade — real module src/js/jobs.js calls renderAsVisual after
 * as-run completes (was a bare closure ref; modules can't reach closure fns). */
try {
  window.__kaleidoAgent = {
    renderAsVisual: renderAsVisual,
  };
} catch (_) {}

export { renderAsVisual, loadEmbedLabStatus, loadEmbedLabEvents };
